module_name: Banner Dest Sellers
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - advertising
  - products
  - best sellers
  - best sales
short_description: The block best sellers module allows you to place best selling products on your home page or right and left columns of your site.
description: description.md
images:
  - image-1.png
  - image-2.png
license: MIT